apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-configmap
data:
  mongo-init.js: |
    db.createUser({
      user: "root",
      pwd: "root",
      roles: [
        {
          role: "readWrite",
          db: "taller"
        }
      ]
    })